### PR TITLE
Initial Sphinx documentation setup

### PR DESCRIPTION
**Pull request by brandonwillard**
This PR provides a basic setup for Sphinx-based documentation.

### CODE REVIEW

**Comment by ricardoV94** [comment]
For newbies like me, could you add a short guide on the wiki on how to generate the docs locally?

**Comment by ricardoV94** [comment]
I didn't touch the `tround` warning because it was added in `theano-0.9`. But that was in 2017 I think... so we can consider it as well

**Comment by brandonwillard** [comment]
> For newbies like me, could you add a short guide on the wiki on how to generate the docs locally?

This PR adds a `docs` target to the `Makefile`; that should perform all the steps necessary to generate the (html) documentation locally.

**Comment by ricardoV94** [comment]
We should make a push on this one, to start adding better documentation and examples

**Comment by brandonwillard** [comment]
> We should make a push on this one, to start adding better documentation and examples

Feel free to take over this PR; I don't know when I'll have time to get back to it.

**Pull request closed without merging**
