### PR TITLE
http→https

### PR DESCRIPTION
**Pull request by maresb**
**Thank you for opening a PR!**

Here are a few important guidelines and requirements to check before your PR can be merged:
+ [ ] There is an informative high-level description of the changes.
+ [ ] The description and/or commit message(s) references the relevant GitHub issue(s).
+ [ ] [`pre-commit`](https://pre-commit.com/#installation) is installed and [set up](https://pre-commit.com/#3-install-the-git-hook-scripts).
+ [ ] The commit messages follow [these guidelines](https://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html).
+ [ ] The commits correspond to [_relevant logical changes_](https://wiki.openstack.org/wiki/GitCommitMessages#Structural_split_of_changes), and there are **no commits that fix changes introduced by other commits in the same branch/BR**.  If your commit description starts with "Fix...", then you're probably making this mistake.
+ [ ] There are tests covering the changes introduced in the PR.

Don't worry, your PR doesn't need to be in perfect order to submit it.  As development progresses and/or reviewers request changes, you can always [rewrite the history](https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History#_rewriting_history) of your feature/PR branches.

If your PR is an ongoing effort and you would like to involve us in the process, simply make it a [draft PR](https://docs.github.com/en/free-pro-team@latest/github/collaborating-with-issues-and-pull-requests/about-pull-requests#draft-pull-requests).

### CODE REVIEW

**Comment by maresb** [comment]
Sorry, I think this is the most ridiculous PR I've ever submitted. :joy: I just noticed this while checking the metadata in relation to the feedstock. Apologies for wasting your time.

**Comment by brandonwillard** [comment]
> Sorry, I think this is the most ridiculous PR I've ever submitted. 😂 I just noticed this while checking the metadata in relation to the feedstock. Apologies for wasting your time.

Are you saying you want to close this?

**Comment by maresb** [comment]
It's embarrassing but valid

**Comment by twiecki** [comment]
Not sure what's up with tests, but it can't be related to this.

@maresb All fixes are much appreciated 👍

**Comment by brandonwillard** [comment]
Don't forget to look at the Git commit message guidelines [here](https://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html).  Since we use the PR titles to auto-generate the release notes, a properly formatted Git commit message can also serve as valid PR titles and release notes, so there's at least one practical reason for all this.

**Comment by maresb** [comment]
@brandonwillard thanks for the tip, and thanks for fixing my title, I'll keep that in mind for the future!

**Pull request merged**
